pool: Agents_ki_duniya

trigger: none

steps:

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'Write-Host "Hello World"'

- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/todoapp_infra'
    backendServiceArm: 'Workload_secure_connection'
    backendAzureRmResourceGroupName: 'azuredevops'
    backendAzureRmStorageAccountName: 'demostorage8250'
    backendAzureRmContainerName: 'anujcontainer'
    backendAzureRmKey: 'anuj.tfstate'
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/todoapp_infra'
    environmentServiceNameAzureRM: 'Workload_secure_connection'